# 1. 在1维array像List一样添加元素

In [5]:
import numpy as np
a = np.array([])
b = [1,2,3]
a = np.append(a, b)
print('a append b\n', a)
c = [4,5,6]
a = np.append(a, c)
print('a append c\n', a)

a append b
 [1. 2. 3.]
a append c
 [1. 2. 3. 4. 5. 6.]


# 2. 2维元素的拼接

In [26]:
import numpy as np
a = np.array([[4,5,6]])
b = np.array([[1,2,3]])
# 0: 按行拼接，1：按列拼接
c = np.append(a, b, axis=0)
print('c\n', c)
d = np.concatenate([a, b], axis=0)
print('d\n', d)

c
 [[4 5 6]
 [1 2 3]]
d
 [[4 5 6]
 [1 2 3]]


# 3. 遍历拼接2维数组

In [1]:
# 方法1：
import numpy as np

a = np.array([[4,5,6]])
b = np.array([[1,2,3]])
c = np.array([[7,8,9]])

flag = True
val_all = None
for item in [a, b, c]:
    if flag:
        flag = False
        val_all = item.copy()
    else:
        # 0: 按行拼接，1：按列拼接
        val_all = np.append(val_all, item, axis=0)
print(val_all)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [2]:
# 方法二: 推荐
import numpy as np

a = np.array([[4,5,6]])
b = np.array([[1,2,3]])
c = np.array([[7,8,9]])
print(a.shape)

val_lst = []
for item in [a, b, c]:
    val_lst.append(item)
val_all = np.concatenate(val_lst, axis=0)
print(val_all)

(1, 3)
[[4 5 6]
 [1 2 3]
 [7 8 9]]
